### ISSUE TITLE
Doesn't works with chinese or japanese.

### ISSUE THREAD

**Issue by sevelee** [slysherz/vscode-comment-box#1]
![image](https://user-images.githubusercontent.com/8036235/49789299-9f8b5400-fd66-11e8-984d-6d9623e117ff.png)

**Comment by sevelee** [comment]
also emoji 
![image](https://user-images.githubusercontent.com/8036235/49789401-e2e5c280-fd66-11e8-84e9-1fe02b858627.png)

**Comment by SlySherZ** [comment]
Hello! Thanks for filling a bug report.

I don't think this problem can be solved completely, even if we pick the right amount of characters, the edges still look off. This happens with every character that takes more or less than 1 mono-space character.

Still, we could do better than we do at the moment, so I'll look into it.
Thanks!

**Comment by sevelee** [comment]
@SlySherZ Thanks for you reply. I figured out too that it's because the font I am using is not perfect two english letter to 1 fullwidth charcter. 
But still this is a wonderfull plugin, thanks for your works.

**Comment by slysherz** [comment]
If someone needs this, I prepared an experimental release that handles these characters with one caveat: it assumes you're using a [duospaced font](https://en.wikipedia.org/wiki/Duospaced_font). If you're using other fonts, it should still look better than it does at the moment, but the characters won't line up perfectly.

You can get the VSIX file [here](https://github.com/slysherz/vscode-comment-box/raw/unicode/vsix_releases/comment-box-1.1.0-unicode.vsix). To install it, go to VSCode -> Extensions -> "..." -> "Install from VSIX ...".

I hope this helps a bit, even though I would like to have a better solution. Please do report back if you've tried it and are having any kind of problems.

**Comment by toge** [comment]
I think your experimental release works fine.
Would you apply this modification to latest release?

**Comment by slysherz** [comment]
I am sorry for taking so long to answer this.

I am currently considering adding support in the live version of the extension, but that involves introducing many possible failure cases. I need to spend more time reviewing the changes.

In the mean time, I prepared a [beta version](https://github.com/slysherz/vscode-comment-box/raw/master/vsix_releases/comment-box-2.1.0-beta.vsix) so that you can use multiple styles with unicode support. Please do report back if you find any problems. Thanks!
