### ISSUE TITLE
Feature request: More style config

### ISSUE THREAD

**Issue by al1-ce** [slysherz/vscode-comment-box#18]
Just a small addition to config to set minimum box size in symbols/lines, so instead of:
```
###########
# COMMENT #
###########
```
It will do:
```
###################################
#             COMMENT             #
###################################
```
Or:
```
###################################
#                                 #
#             COMMENT             #
#                                 #
###################################
```

**Comment by al1-ce** [comment]
Also maybe some symbol configs for empty lines?
Like so:
```
/*┌────────────────────────────┐  
  │ Lorem ipsum dolor sit amet │
  │        comments here       │  
  ├────────────────────────────┤  
  │      after empty line      │ 
  └────────────────────────────┘*/
```

**Comment by slysherz** [comment]
Hello! I noticed you've closed this issue, but still I would like to add a little context about what I did / didn't do.

I've added 2 settings that allow what your first comment suggests. `boxWidth` for 
```
###################################
#             COMMENT             #
###################################
```

and `removeEmptyLines` for 
```
###########
#         #
# COMMENT #
#         #
###########
```

As for the last suggestion, I considered them but there are a few problems:
- it makes the configuration more complicated, I'd prefer less options if possible
- I don't think people need this a lot (I could be wrong)
- most importantly, it takes a while to implement because it interacts badly with the need to detect comment boxes, and I don't have much time to spend on this

Thanks for the suggestions, and if you really need that last one please let me know : )
